services:
  - type: web
    name: ml-project
    env: python
    plan: free
    buildCommand: pip install -r requirements-render.txt
    startCommand: gunicorn app:app
    autoDeploy: true
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
